# Generated by Django 2.1.1 on 2018-11-29 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='movies.Person', verbose_name='director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='key_actors',
            field=models.ManyToManyField(blank=True, related_name='acted_movies', to='movies.Person', verbose_name='list of key actors'),
        ),
    ]
