# Generated by Django 2.1.1 on 2018-12-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20181129_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionrole',
            options={'ordering': ['title'], 'verbose_name_plural': 'production role'},
        ),
    ]
