# Generated by Django 2.1.1 on 2018-12-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20181219_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, limit_choices_to={'production_roles': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='movies.Person', verbose_name='director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='key_actors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'production_roles': 1}, related_name='acted_movies', to='movies.Person', verbose_name='list of key actors'),
        ),
    ]
