# Generated by Django 2.1.1 on 2018-12-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
