# Generated by Django 2.1.1 on 2019-01-01 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_person_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 11, 24, 32, 945714)),
        ),
    ]
