# Generated by Django 2.1.1 on 2019-01-03 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0010_auto_20190101_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='down_users',
            field=models.ManyToManyField(blank=True, related_name='down_user_comment', to=settings.AUTH_USER_MODEL, verbose_name='down_user of comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_users',
            field=models.ManyToManyField(blank=True, related_name='up_user_comment', to=settings.AUTH_USER_MODEL, verbose_name='up_vote of comment'),
        ),
    ]
