# Generated by Django 2.1.1 on 2019-01-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_person_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_zh',
            field=models.CharField(default='', max_length=50),
        ),
    ]
